# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlightFinder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlightFinder
  # networking
  pod 'ReachabilitySwift', '~> 4.1.0'
  pod 'Moya', '~> 10.0'
  # database
  pod 'RealmSwift'
  # activity indicator
  pod 'PKHUD', '~> 5.0'
  # in-app notification banners
  pod 'NotificationBannerSwift'

  target 'FlightFinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlightFinderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
